services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    environment:
      DB_USER: user
      DB_PASS: pass
      DB_PROD_HOST: db_prod
      DB_TEST_HOST: db_test
      DB_PROD_NAME: prod
      DB_TEST_NAME: test
    depends_on:
      - db_prod
      - db_test
    networks:
      - inft2201_network

  db_prod:
    image: postgres:16
    environment:
      POSTGRES_DB: prod
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./init-prod:/docker-entrypoint-initdb.d
    networks:
      - inft2201_network

  db_test:
    image: postgres:16
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    networks:
      - inft2201_network

networks:
  inft2201_network:
    driver: bridge